[2021-12-28 20:13:55,163] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.cleanse_kym 2021-12-27T20:13:54.304938+00:00 [queued]>
[2021-12-28 20:13:55,180] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.cleanse_kym 2021-12-27T20:13:54.304938+00:00 [queued]>
[2021-12-28 20:13:55,181] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 20:13:55,181] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-28 20:13:55,182] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 20:13:55,191] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): cleanse_kym> on 2021-12-27T20:13:54.304938+00:00
[2021-12-28 20:13:55,195] {standard_task_runner.py:52} INFO - Started process 2183 to run task
[2021-12-28 20:13:55,199] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cleansing_dag', 'cleanse_kym', '2021-12-27T20:13:54.304938+00:00', '--job-id', '296', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmp5zt3y6sf', '--error-file', '/tmp/tmp8cwpnlqz']
[2021-12-28 20:13:55,200] {standard_task_runner.py:77} INFO - Job 296: Subtask cleanse_kym
[2021-12-28 20:13:55,240] {logging_mixin.py:109} INFO - Running <TaskInstance: cleansing_dag.cleanse_kym 2021-12-27T20:13:54.304938+00:00 [running]> on host 62c7f391d30e
[2021-12-28 20:13:55,293] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=cleanse_kym
AIRFLOW_CTX_EXECUTION_DATE=2021-12-27T20:13:54.304938+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-27T20:13:54.304938+00:00
[2021-12-28 20:16:40,898] {python.py:151} INFO - Done. Returned value was: None
[2021-12-28 20:16:40,938] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=cleanse_kym, execution_date=20211227T201354, start_date=20211228T201355, end_date=20211228T201640
[2021-12-28 20:16:40,987] {local_task_job.py:151} INFO - Task exited with return code 0
