[2021-12-28 20:08:16,337] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.merge 2021-12-27T20:05:08.090968+00:00 [queued]>
[2021-12-28 20:08:16,359] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.merge 2021-12-27T20:05:08.090968+00:00 [queued]>
[2021-12-28 20:08:16,360] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 20:08:16,360] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-28 20:08:16,361] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 20:08:16,376] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): merge> on 2021-12-27T20:05:08.090968+00:00
[2021-12-28 20:08:16,382] {standard_task_runner.py:52} INFO - Started process 2060 to run task
[2021-12-28 20:08:16,384] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cleansing_dag', 'merge', '2021-12-27T20:05:08.090968+00:00', '--job-id', '283', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmpylubbz9p', '--error-file', '/tmp/tmp1kof7c0t']
[2021-12-28 20:08:16,385] {standard_task_runner.py:77} INFO - Job 283: Subtask merge
[2021-12-28 20:08:16,424] {logging_mixin.py:109} INFO - Running <TaskInstance: cleansing_dag.merge 2021-12-27T20:05:08.090968+00:00 [running]> on host 62c7f391d30e
[2021-12-28 20:08:16,593] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=merge
AIRFLOW_CTX_EXECUTION_DATE=2021-12-27T20:05:08.090968+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-27T20:05:08.090968+00:00
[2021-12-28 20:08:17,040] {python.py:151} INFO - Done. Returned value was: None
[2021-12-28 20:08:17,052] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=merge, execution_date=20211227T200508, start_date=20211228T200816, end_date=20211228T200817
[2021-12-28 20:08:17,121] {local_task_job.py:151} INFO - Task exited with return code 0
