[2021-11-07 15:52:57,398] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.addSafeSearchRows 2021-11-07T15:52:53.391359+00:00 [None]>
[2021-11-07 15:52:57,412] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.addSafeSearchRows 2021-11-07T15:52:53.391359+00:00 [None]>
[2021-11-07 15:52:57,413] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-11-07 15:52:57,414] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-11-07 15:52:57,414] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-11-07 15:52:57,424] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): addSafeSearchRows> on 2021-11-07T15:52:53.391359+00:00
[2021-11-07 15:52:57,428] {standard_task_runner.py:52} INFO - Started process 53 to run task
[2021-11-07 15:52:57,431] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'addSafeSearchRows', '2021-11-07T15:52:53.391359+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp0gm2hehw', '--error-file', '/tmp/tmphl6b66ax']
[2021-11-07 15:52:57,431] {standard_task_runner.py:77} INFO - Job 8: Subtask addSafeSearchRows
[2021-11-07 15:52:57,468] {logging_mixin.py:104} INFO - Running <TaskInstance: first_dag.addSafeSearchRows 2021-11-07T15:52:53.391359+00:00 [running]> on host c6854056e93d
[2021-11-07 15:52:57,505] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=addSafeSearchRows
AIRFLOW_CTX_EXECUTION_DATE=2021-11-07T15:52:53.391359+00:00
[2021-11-07 15:54:17,533] {taskinstance.py:1455} ERROR - Object of type 'DataFrame' is not JSON serializable
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dag.py", line 34, in addSafeSearchRows
    json.dump(df, f, ensure_ascii=False)
  File "/usr/local/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2021-11-07 15:54:17,541] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=addSafeSearchRows, execution_date=20211107T155253, start_date=20211107T155257, end_date=20211107T155417
[2021-11-07 15:54:17,636] {local_task_job.py:146} INFO - Task exited with return code 1
