[2021-12-13 14:11:17,666] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: cleansing_dag.writeOut 2021-12-13T14:11:17.010271+00:00 [queued]>
[2021-12-13 14:11:17,687] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: cleansing_dag.writeOut 2021-12-13T14:11:17.010271+00:00 [queued]>
[2021-12-13 14:11:17,688] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 14:11:17,688] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-12-13 14:11:17,689] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 14:11:17,700] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): writeOut> on 2021-12-13T14:11:17.010271+00:00
[2021-12-13 14:11:17,704] {standard_task_runner.py:52} INFO - Started process 61 to run task
[2021-12-13 14:11:17,707] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'cleansing_dag', 'writeOut', '2021-12-13T14:11:17.010271+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmpwn2te8ah', '--error-file', '/tmp/tmpb7i2120m']
[2021-12-13 14:11:17,709] {standard_task_runner.py:77} INFO - Job 8: Subtask writeOut
[2021-12-13 14:11:17,744] {logging_mixin.py:104} INFO - Running <TaskInstance: cleansing_dag.writeOut 2021-12-13T14:11:17.010271+00:00 [running]> on host b9654409f9ea
[2021-12-13 14:11:17,783] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=writeOut
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T14:11:17.010271+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-13T14:11:17.010271+00:00
[2021-12-13 14:11:17,802] {taskinstance.py:1455} ERROR - kym_vision_processed.parquet
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kym_cleansing.py", line 170, in writeOutToParquet
    df = pd.read_parquet('kym_vision_processed.parquet', engine='pyarrow')
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 317, in read_parquet
    return impl.read(path, columns=columns, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 142, in read
    path, columns=columns, filesystem=fs, **kwargs
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/parquet.py", line 1915, in read_table
    coerce_int96_timestamp_unit=coerce_int96_timestamp_unit
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/parquet.py", line 1729, in __init__
    ignore_prefixes=ignore_prefixes)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/dataset.py", line 680, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/dataset.py", line 425, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/dataset.py", line 401, in _ensure_single_source
    raise FileNotFoundError(path)
FileNotFoundError: kym_vision_processed.parquet
[2021-12-13 14:11:17,808] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=cleansing_dag, task_id=writeOut, execution_date=20211213T141117, start_date=20211213T141117, end_date=20211213T141117
[2021-12-13 14:11:17,840] {local_task_job.py:146} INFO - Task exited with return code 1
