[2021-11-21 18:12:36,817] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.writeOut 2021-11-20T18:11:09.696138+00:00 [queued]>
[2021-11-21 18:12:36,845] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.writeOut 2021-11-20T18:11:09.696138+00:00 [queued]>
[2021-11-21 18:12:36,846] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 18:12:36,846] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-11-21 18:12:36,846] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 18:12:36,860] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): writeOut> on 2021-11-20T18:11:09.696138+00:00
[2021-11-21 18:12:36,865] {standard_task_runner.py:52} INFO - Started process 55 to run task
[2021-11-21 18:12:36,868] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'writeOut', '2021-11-20T18:11:09.696138+00:00', '--job-id', '33', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpwf34gk3e', '--error-file', '/tmp/tmphvt4sl3o']
[2021-11-21 18:12:36,870] {standard_task_runner.py:77} INFO - Job 33: Subtask writeOut
[2021-11-21 18:12:36,909] {logging_mixin.py:104} INFO - Running <TaskInstance: first_dag.writeOut 2021-11-20T18:11:09.696138+00:00 [running]> on host 5212096de831
[2021-11-21 18:12:36,951] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=writeOut
AIRFLOW_CTX_EXECUTION_DATE=2021-11-20T18:11:09.696138+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-20T18:11:09.696138+00:00
[2021-11-21 18:12:54,991] {python.py:118} INFO - Done. Returned value was: None
[2021-11-21 18:12:55,022] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=writeOut, execution_date=20211120T181109, start_date=20211121T181236, end_date=20211121T181255
[2021-11-21 18:12:55,048] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-21 18:12:55,106] {local_task_job.py:146} INFO - Task exited with return code 0
