[2021-12-29 14:10:53,439] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.create_fact_table_query 2021-12-29T13:56:44.064632+00:00 [queued]>
[2021-12-29 14:10:53,457] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.create_fact_table_query 2021-12-29T13:56:44.064632+00:00 [queued]>
[2021-12-29 14:10:53,458] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 14:10:53,458] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-29 14:10:53,458] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 14:10:53,468] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): create_fact_table_query> on 2021-12-29T13:56:44.064632+00:00
[2021-12-29 14:10:53,473] {standard_task_runner.py:52} INFO - Started process 5014 to run task
[2021-12-29 14:10:53,476] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cleansing_dag', 'create_fact_table_query', '2021-12-29T13:56:44.064632+00:00', '--job-id', '424', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmptpupcvm9', '--error-file', '/tmp/tmpd0k2k5ji']
[2021-12-29 14:10:53,477] {standard_task_runner.py:77} INFO - Job 424: Subtask create_fact_table_query
[2021-12-29 14:10:53,515] {logging_mixin.py:109} INFO - Running <TaskInstance: cleansing_dag.create_fact_table_query 2021-12-29T13:56:44.064632+00:00 [running]> on host 34521d0e1651
[2021-12-29 14:10:53,565] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=create_fact_table_query
AIRFLOW_CTX_EXECUTION_DATE=2021-12-29T13:56:44.064632+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-29T13:56:44.064632+00:00
[2021-12-29 14:10:55,424] {python.py:151} INFO - Done. Returned value was: None
[2021-12-29 14:10:55,435] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=create_fact_table_query, execution_date=20211229T135644, start_date=20211229T141053, end_date=20211229T141055
[2021-12-29 14:10:55,455] {local_task_job.py:151} INFO - Task exited with return code 0
