[2021-12-31 15:11:43,195] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main_dag.create_fact_table_query 2021-12-31T15:06:37.773378+00:00 [queued]>
[2021-12-31 15:11:43,209] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main_dag.create_fact_table_query 2021-12-31T15:06:37.773378+00:00 [queued]>
[2021-12-31 15:11:43,209] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 15:11:43,210] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-31 15:11:43,210] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 15:11:43,226] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): create_fact_table_query> on 2021-12-31T15:06:37.773378+00:00
[2021-12-31 15:11:43,233] {standard_task_runner.py:52} INFO - Started process 14148 to run task
[2021-12-31 15:11:43,236] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_fact_table_query', '2021-12-31T15:06:37.773378+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpg1jpl34e', '--error-file', '/tmp/tmp680d7k7k']
[2021-12-31 15:11:43,237] {standard_task_runner.py:77} INFO - Job 44: Subtask create_fact_table_query
[2021-12-31 15:11:43,279] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.create_fact_table_query 2021-12-31T15:06:37.773378+00:00 [running]> on host 8e99a5d40b8f
[2021-12-31 15:11:43,342] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_fact_table_query
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T15:06:37.773378+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-31T15:06:37.773378+00:00
[2021-12-31 15:11:45,248] {python.py:151} INFO - Done. Returned value was: None
[2021-12-31 15:11:45,263] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_fact_table_query, execution_date=20211231T150637, start_date=20211231T151143, end_date=20211231T151145
[2021-12-31 15:11:45,297] {local_task_job.py:151} INFO - Task exited with return code 0
