[2021-12-31 16:35:12,213] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main_dag.create_fact_table_query 2021-12-31T16:29:52.816585+00:00 [queued]>
[2021-12-31 16:35:12,230] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main_dag.create_fact_table_query 2021-12-31T16:29:52.816585+00:00 [queued]>
[2021-12-31 16:35:12,231] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 16:35:12,232] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-31 16:35:12,232] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 16:35:12,253] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): create_fact_table_query> on 2021-12-31T16:29:52.816585+00:00
[2021-12-31 16:35:12,262] {standard_task_runner.py:52} INFO - Started process 5813 to run task
[2021-12-31 16:35:12,266] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_fact_table_query', '2021-12-31T16:29:52.816585+00:00', '--job-id', '223', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmplg4tkj7r', '--error-file', '/tmp/tmpbc0da375']
[2021-12-31 16:35:12,267] {standard_task_runner.py:77} INFO - Job 223: Subtask create_fact_table_query
[2021-12-31 16:35:12,325] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.create_fact_table_query 2021-12-31T16:29:52.816585+00:00 [running]> on host 8e99a5d40b8f
[2021-12-31 16:35:12,394] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_fact_table_query
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T16:29:52.816585+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-31T16:29:52.816585+00:00
[2021-12-31 16:35:14,364] {python.py:151} INFO - Done. Returned value was: None
[2021-12-31 16:35:14,376] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_fact_table_query, execution_date=20211231T162952, start_date=20211231T163512, end_date=20211231T163514
[2021-12-31 16:35:14,408] {local_task_job.py:151} INFO - Task exited with return code 0
