[2021-12-13 15:00:13,935] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: cleansing_dag.writeOut 2021-12-13T14:58:18.553312+00:00 [queued]>
[2021-12-13 15:00:13,959] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: cleansing_dag.writeOut 2021-12-13T14:58:18.553312+00:00 [queued]>
[2021-12-13 15:00:13,960] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 15:00:13,960] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-12-13 15:00:13,961] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 15:00:13,971] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): writeOut> on 2021-12-13T14:58:18.553312+00:00
[2021-12-13 15:00:13,975] {standard_task_runner.py:52} INFO - Started process 14260 to run task
[2021-12-13 15:00:13,978] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'cleansing_dag', 'writeOut', '2021-12-13T14:58:18.553312+00:00', '--job-id', '27', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmpdrr39v3q', '--error-file', '/tmp/tmpxmzi4pc7']
[2021-12-13 15:00:13,979] {standard_task_runner.py:77} INFO - Job 27: Subtask writeOut
[2021-12-13 15:00:14,018] {logging_mixin.py:104} INFO - Running <TaskInstance: cleansing_dag.writeOut 2021-12-13T14:58:18.553312+00:00 [running]> on host c2664a5050de
[2021-12-13 15:00:14,054] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=writeOut
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T14:58:18.553312+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-13T14:58:18.553312+00:00
[2021-12-13 15:00:14,244] {python.py:118} INFO - Done. Returned value was: None
[2021-12-13 15:00:14,269] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=writeOut, execution_date=20211213T145818, start_date=20211213T150013, end_date=20211213T150014
[2021-12-13 15:00:14,349] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-13 15:00:14,392] {local_task_job.py:146} INFO - Task exited with return code 0
