[2021-12-30 16:21:01,325] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.insert_type_dimension_query 2021-12-29T16:17:32.767228+00:00 [queued]>
[2021-12-30 16:21:01,389] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.insert_type_dimension_query 2021-12-29T16:17:32.767228+00:00 [queued]>
[2021-12-30 16:21:01,390] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-30 16:21:01,390] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-30 16:21:01,391] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-30 16:21:01,402] {taskinstance.py:1114} INFO - Executing <Task(PostgresOperator): insert_type_dimension_query> on 2021-12-29T16:17:32.767228+00:00
[2021-12-30 16:21:01,410] {standard_task_runner.py:52} INFO - Started process 7029 to run task
[2021-12-30 16:21:01,414] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cleansing_dag', 'insert_type_dimension_query', '2021-12-29T16:17:32.767228+00:00', '--job-id', '13', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmpcis7ite4', '--error-file', '/tmp/tmpf76xcc_i']
[2021-12-30 16:21:01,415] {standard_task_runner.py:77} INFO - Job 13: Subtask insert_type_dimension_query
[2021-12-30 16:21:01,460] {logging_mixin.py:109} INFO - Running <TaskInstance: cleansing_dag.insert_type_dimension_query 2021-12-29T16:17:32.767228+00:00 [running]> on host 71257c6b2a25
[2021-12-30 16:21:01,515] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=insert_type_dimension_query
AIRFLOW_CTX_EXECUTION_DATE=2021-12-29T16:17:32.767228+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-29T16:17:32.767228+00:00
[2021-12-30 16:21:01,516] {postgres.py:68} INFO - Executing: CREATE TABLE IF NOT EXISTS type_dimension (
type_id INT PRIMARY KEY,
meme_type TEXT);INSERT INTO type_dimension VALUES ('0', 'No type') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('1', 'snowclone') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('2', 'pop-culture-reference') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('3', 'song') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('4', 'viral-video') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('5', 'dance') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('6', 'catchphrase') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('7', 'image-macro') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('8', 'slang') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('9', 'participatory-media') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('10', 'shock-media') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('11', 'visual-effect') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('12', 'parody') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('13', 'remix') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('14', 'character') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('15', 'hoax') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('16', 'advertisement') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('17', 'reaction') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('18', 'copypasta') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('19', 'social-game') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('20', 'axiom') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('21', 'optical-illusion') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('22', 'photoshop') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('23', 'emoticon') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('24', 'animal') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('25', 'creepypasta') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('26', 'sound-effect') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('27', 'lip-dub') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('28', 'fan-labor') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('29', 'fan-art') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('30', 'conspiracy-theory') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('31', 'viral-debate') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('32', 'hashtag') ON CONFLICT (type_id) DO NOTHING;
INSERT INTO type_dimension VALUES ('33', 'cliche') ON CONFLICT (type_id) DO NOTHING;
[2021-12-30 16:21:01,532] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/operators/postgres.py", line 70, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 177, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 88, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 379, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2021-12-30 16:21:01,536] {taskinstance.py:1505} INFO - Marking task as UP_FOR_RETRY. dag_id=cleansing_dag, task_id=insert_type_dimension_query, execution_date=20211229T161732, start_date=20211230T162101, end_date=20211230T162101
[2021-12-30 16:21:01,587] {local_task_job.py:151} INFO - Task exited with return code 1
